title: Diário de Bordo - Ciência da Computação UDF
description: Acompanhamento diário das aulas e aprendizados no curso de Computação
theme: minima
language: pt-BR

permalink: /:year/:month/:day/:title/

author:
  name: Lucas
  email: your.email@example.com

markdown: kramdown
highlighter: rouge

github_username: Lucasdoreac

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap