title: My Course Diary
description: Daily insights and progress in my computer science journey
theme: minima

permalinks:
  posts: /:year/:month/:day/:title/

authors:
  lucas:
    name: Lucas
    display_name: Lucas
    email: your.email@example.com
    web: https://github.com/Lucasdoreac

default_author: lucas

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap